/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface WriteResult {
    ok: boolean;
    message: string;
}
export interface FirmSummary {
    ownerEmail: string;
    status: string;
    ownerName: string;
    firmNumber: string;
    clientCount: bigint;
    firmName: string;
    firmId: FirmId;
    lastLogin: bigint;
    planType: string;
    ownerMobile: string;
}
export interface ScanResult {
    ok: boolean;
    totalRecordsScanned: bigint;
    assigned: bigint;
    skipped: boolean;
    hadFirmId: bigint;
    missingFirmId: bigint;
    unmatched: bigint;
    message: string;
    perFirmDetails: Array<FirmAssignmentDetail>;
}
export interface FirmAssignmentDetail {
    assigned: bigint;
    firmNumber: string;
    firmId: FirmId;
}
export interface MigrationResult {
    ok: boolean;
    perFirmCounts: Array<FirmMigrationCount>;
    skipped: boolean;
    message: string;
    orphanedCount: bigint;
    totalRecords: bigint;
}
export interface FirmMigrationCount {
    firmNumber: string;
    firmId: FirmId;
    recordCount: bigint;
}
export interface WriteContext {
    userId: string;
    role: string;
    firmId: FirmId;
}
export type FirmId = string;
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    backfillFirmNumbers(): Promise<bigint>;
    forceRecoverFirmData(adminRole: string, targetFirmId: FirmId, appDataPayload: string, recordCount: bigint): Promise<WriteResult>;
    getActiveFirmAppData(firmId: FirmId, role: string): Promise<string>;
    getAllFirmSummaries(adminRole: string): Promise<Array<FirmSummary>>;
    getAutoAssignStatus(): Promise<{
        migratedRecords: bigint;
        autoAssignVersion: bigint;
        autoAssignRan: boolean;
        adminFirmId: string;
    }>;
    getCallerUserRole(): Promise<UserRole>;
    getFirmAppData(firmId: FirmId, role: string): Promise<string>;
    getFirmAppDataCount(): Promise<bigint>;
    getFirmUserData(firmId: FirmId, role: string): Promise<string>;
    getGlobalAppData(): Promise<string>;
    getGlobalUserDatabase(): Promise<string>;
    getMigrationStatus(): Promise<{
        migratedRecords: bigint;
        autoAssignVersion: bigint;
        migrated: boolean;
        autoAssignRan: boolean;
        migrationVersion: bigint;
        adminFirmId: string;
    }>;
    getMigrationVersion(): Promise<bigint>;
    getNextFirmNumber(firmId: FirmId): Promise<string>;
    isCallerAdmin(): Promise<boolean>;
    migrateExistingDataToAdminFirm(adminFirmId: FirmId, existingAppData: string, existingUserDb: string): Promise<WriteResult>;
    migratePreIsolationData(adminRole: string, adminFirmId: FirmId, firmPartitions: Array<[FirmId, string]>, orphanedAppData: string, orphanedCount: bigint, auditEntry: string): Promise<MigrationResult>;
    needsAutoAssign(): Promise<boolean>;
    peekNextFirmNumber(): Promise<string>;
    registerFirm(firmId: FirmId, firmName: string, ownerName: string, ownerEmail: string, ownerMobile: string): Promise<WriteResult>;
    resetAutoAssign(adminRole: string): Promise<WriteResult>;
    saveFirmAppData(ctx: WriteContext, payload: string): Promise<WriteResult>;
    saveFirmUserData(ctx: WriteContext, payload: string): Promise<WriteResult>;
    saveGlobalAppData(json: string): Promise<void>;
    saveGlobalUserDatabase(json: string): Promise<void>;
    scanAndAutoAssignFirmIds(adminRole: string, adminFirmId: FirmId, firmPartitions: Array<[FirmId, string, bigint]>, orphanedPayload: string, totalScanned: bigint, hadFirmId: bigint, missingFirmId: bigint, unmatched: bigint, force: boolean): Promise<ScanResult>;
    updateFirmPlan(adminRole: string, targetFirmId: FirmId, planType: string, status: string): Promise<WriteResult>;
}
import type { UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async backfillFirmNumbers(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.backfillFirmNumbers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.backfillFirmNumbers();
            return result;
        }
    }
    async forceRecoverFirmData(arg0: string, arg1: FirmId, arg2: string, arg3: bigint): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.forceRecoverFirmData(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.forceRecoverFirmData(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getActiveFirmAppData(arg0: FirmId, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveFirmAppData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveFirmAppData(arg0, arg1);
            return result;
        }
    }
    async getAllFirmSummaries(arg0: string): Promise<Array<FirmSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFirmSummaries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFirmSummaries(arg0);
            return result;
        }
    }
    async getAutoAssignStatus(): Promise<{
        migratedRecords: bigint;
        autoAssignVersion: bigint;
        autoAssignRan: boolean;
        adminFirmId: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAutoAssignStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAutoAssignStatus();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFirmAppData(arg0: FirmId, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirmAppData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirmAppData(arg0, arg1);
            return result;
        }
    }
    async getFirmAppDataCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirmAppDataCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirmAppDataCount();
            return result;
        }
    }
    async getFirmUserData(arg0: FirmId, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getFirmUserData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFirmUserData(arg0, arg1);
            return result;
        }
    }
    async getGlobalAppData(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalAppData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalAppData();
            return result;
        }
    }
    async getGlobalUserDatabase(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getGlobalUserDatabase();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGlobalUserDatabase();
            return result;
        }
    }
    async getMigrationStatus(): Promise<{
        migratedRecords: bigint;
        autoAssignVersion: bigint;
        migrated: boolean;
        autoAssignRan: boolean;
        migrationVersion: bigint;
        adminFirmId: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMigrationStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMigrationStatus();
            return result;
        }
    }
    async getMigrationVersion(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getMigrationVersion();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMigrationVersion();
            return result;
        }
    }
    async getNextFirmNumber(arg0: FirmId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getNextFirmNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNextFirmNumber(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async migrateExistingDataToAdminFirm(arg0: FirmId, arg1: string, arg2: string): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.migrateExistingDataToAdminFirm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migrateExistingDataToAdminFirm(arg0, arg1, arg2);
            return result;
        }
    }
    async migratePreIsolationData(arg0: string, arg1: FirmId, arg2: Array<[FirmId, string]>, arg3: string, arg4: bigint, arg5: string): Promise<MigrationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.migratePreIsolationData(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.migratePreIsolationData(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async needsAutoAssign(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.needsAutoAssign();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.needsAutoAssign();
            return result;
        }
    }
    async peekNextFirmNumber(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.peekNextFirmNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.peekNextFirmNumber();
            return result;
        }
    }
    async registerFirm(arg0: FirmId, arg1: string, arg2: string, arg3: string, arg4: string): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFirm(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFirm(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async resetAutoAssign(arg0: string): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.resetAutoAssign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetAutoAssign(arg0);
            return result;
        }
    }
    async saveFirmAppData(arg0: WriteContext, arg1: string): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFirmAppData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFirmAppData(arg0, arg1);
            return result;
        }
    }
    async saveFirmUserData(arg0: WriteContext, arg1: string): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.saveFirmUserData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveFirmUserData(arg0, arg1);
            return result;
        }
    }
    async saveGlobalAppData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGlobalAppData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGlobalAppData(arg0);
            return result;
        }
    }
    async saveGlobalUserDatabase(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGlobalUserDatabase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGlobalUserDatabase(arg0);
            return result;
        }
    }
    async scanAndAutoAssignFirmIds(arg0: string, arg1: FirmId, arg2: Array<[FirmId, string, bigint]>, arg3: string, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: boolean): Promise<ScanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.scanAndAutoAssignFirmIds(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanAndAutoAssignFirmIds(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateFirmPlan(arg0: string, arg1: FirmId, arg2: string, arg3: string): Promise<WriteResult> {
        if (this.processError) {
            try {
                const result = await this.actor.updateFirmPlan(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateFirmPlan(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
